# Generated by Django 3.1.6 on 2021-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyPots',
            fields=[
                ('honeyPotID', models.AutoField(primary_key=True, serialize=False)),
                ('honeyPotType', models.IntegerField()),
                ('ThreatNum', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('honeyPotID', models.IntegerField()),
                ('honeyPotType', models.IntegerField()),
                ('env', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=30)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIP',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatType',
            fields=[
                ('threatID', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
