# Generated by Django 3.1.6 on 2021-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypots',
            name='port',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
