# Generated by Django 3.1.6 on 2021-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_honeypots_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='env',
        ),
        migrations.AddField(
            model_name='honeypots',
            name='IsIntranet',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
